load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "runnerPackageC",
    srcs = ["Runner.java"],
    main_class = "com.example.cmdline.Runner",
    deps = ["//:greetingPackageC"],
)
